from __future__ import annotations

from fluidics_gui.app import create_app


def sample_payload():
    return {
        "name": "T junction / test",
        "design": {
            "shapes": [
                {"type": "line", "x1": 5, "y1": 12.5, "x2": 60, "y2": 12.5, "width": 0.8},
                {"type": "line", "x1": 30, "y1": 3, "x2": 30, "y2": 12.5, "width": 0.8},
            ]
        },
        "settings": {},
    }


def test_editor_and_health_endpoints():
    client = create_app({"TESTING": True}).test_client()

    page = client.get("/")
    assert page.status_code == 200
    assert b"Fluidics Studio" in page.data
    assert client.get("/api/health").json["ok"] is True


def test_preview_and_gcode_endpoints():
    client = create_app({"TESTING": True}).test_client()

    preview = client.post("/api/slice", json=sample_payload())
    assert preview.status_code == 200
    assert preview.json["stats"]["pathCount"] >= 1

    gcode = client.post("/api/gcode", json=sample_payload())
    assert gcode.status_code == 200
    assert gcode.mimetype == "text/x.gcode"
    assert "T-junction-test.gcode" in gcode.headers["Content-Disposition"]
    assert b"generated by Fluidics Studio" in gcode.data


def test_bad_design_is_a_json_400():
    client = create_app({"TESTING": True}).test_client()
    response = client.post("/api/slice", json={"design": {"shapes": []}})

    assert response.status_code == 400
    assert "error" in response.json
